platform :ios, '14.0'
use_frameworks!

target 'ShowPathApp' do
  pod 'RxAlamofire', '6.1.1'
  pod 'RxCocoa', '6.5.0'
  pod 'RxSwift', '6.5.0'
  pod 'SnapKit', '5.6.0'
  pod 'Swinject', '2.8.3'
  pod 'XCGLogger', '7.0.1'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
  end
 end
end